//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wu2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wuEntities1 : DbContext
    {
        public wuEntities1()
            : base("name=wuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLogs> ActivityLogs { get; set; }
        public virtual DbSet<Debts> Debts { get; set; }
        public virtual DbSet<ExpenseDetails> ExpenseDetails { get; set; }
        public virtual DbSet<ExpensePayers> ExpensePayers { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<GroupMembers> GroupMembers { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<MessageReadStatus> MessageReadStatus { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Notices> Notices { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
